title: API Security Village 
description: "<b>API</b> Security Village - BSides SF 2024"
baseurl: ""
url: https://jbahire.github.io/api-security-village-bsides

remote_theme: piazzai/jekyll-nagymaros@v1.1.0

copyright: API Security Community
indexing: true

permalink: pretty

exclude:
    - LICENSE
    - README.md
